services:
  - type: web
    name: paravolley-mpumalanga
    runtime: docker
    plan: free
    region: frankfurt
    branch: thapelo-android-api-integration
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health/ready
    autoDeployTrigger: commit
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        sync: false
      - key: Jwt__Key
        sync: false
      - key: Jwt__Issuer
        value: ParaVolley
      - key: Jwt__Audience
        value: ParaVolleyMobile
